site_name: ToDone API Documentation
nav:
  - lab1:
    - Main: index.md
    - Models: models.md
    - Shemas: schemas.md
    - User API:
        - 'User Endpoints': user_endpoints.md
    - Task API:
        - 'Task Endpoints': task_endpoints.md
  - lab2:
      - task1: task1.md
      - task2: task2.md
theme:
  name: material
  palette:
    primary: 'blue'
    accent: 'light blue'
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
docs_dir: docs
site_dir: site



